apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-conversao-temp
spec:
  selector:
    matchLabels:
      app: dep-conversao-temp
  replicas: 3
  template:
    metadata:
      labels: 
        app: dep-conversao-temp
    spec:
      containers:
        - name: dep-conversao-temp
          image: ronaldobc/conversao-temperatura:v2
          ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: service-conversao-temp
spec:
  selector:
    app: dep-conversao-temp
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30000
  type: NodePort
